ALTER TABLE subscribers ADD COLUMN IF NOT EXISTS source_page TEXT DEFAULT '';
ALTER TABLE subscribers ADD COLUMN IF NOT EXISTS referrer TEXT DEFAULT '';
ALTER TABLE subscribers ADD COLUMN IF NOT EXISTS ip_address TEXT DEFAULT '';
ALTER TABLE subscribers ADD COLUMN IF NOT EXISTS city TEXT DEFAULT '';
ALTER TABLE subscribers ADD COLUMN IF NOT EXISTS country TEXT DEFAULT '';
ALTER TABLE subscribers ADD COLUMN IF NOT EXISTS user_agent TEXT DEFAULT '';
